spring:
  application:
    name: SERVICIO-SINCRONIZACION
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
    virtual-host: /
    connection-timeout: 60000

server:
  port: ${SERVER_PORT:8084}
  error:
    include-stacktrace: never
    include-message: always

reloj:
  intervalo: ${RELOJ_INTERVALO:10}

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.amqp: DEBUG
    com.rabbitmq.client: DEBUG
    org.springframework.boot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always